In [1]:
import numpy as np

###  Why numpy

1. Its fast as its optimisation is written in c language.
2. Backbone of other scientific packages
3. It uses vectorisation using broadcasting ( avoiding loops )

### Datatypes & Attributes

In [2]:
# Main datatype is ndarray where nd stands for n dimensional array

In [27]:
# Creating a numpy array 

a1 = np.array([1,2,3,4])
a1

array([1, 2, 3, 4])

In [28]:
type(a1)

numpy.ndarray

In [8]:
a2 = np.array([[1,2,0.5] , [3,4,0.9]])

In [23]:
a3 = np.array([[[1,2,3] , [4,5,6] ,[7,8,9]],
              [[10,11,12] , [13,14,15] , [16,17,18]]])

In [11]:
# In 1-D shape is just number of elements in it
a1.shape

(4,)

In [12]:
# 2 rows 3 columns
a2.shape

(2, 3)

In [13]:
# axis 0 , axis 1 , axis n
a3.shape

(2, 3, 3)

In [15]:
# Simply gives the dimension of the array
a1.ndim , a2.ndim , a3.ndim

(1, 2, 3)

In [17]:
a1.dtype , a2.dtype , a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [19]:
# Number of elements in the array
a1.size , a2.size , a3.size 

(4, 6, 18)

In [20]:
# all the data in numpy array are ndarray no matter the type and shape of it 

In [21]:
import pandas as pd

In [22]:
df = pd.DataFrame(a2)

In [23]:
df

0    1    2
0  1.0  2.0  0.5
1  3.0  4.0  0.9

In [1]:
# Creating arrays filled  with ones
import numpy as np 

# Press shift tab to view the funtions doc string

In [2]:
one = np.ones((3,3))
one

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [3]:
zero = np.zeros((3,3))
zero

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [6]:
# Works as a array initialisation with given steps
range_array = np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])

In [9]:
random_array = np.random.randint(2 , 92 , (2,3))
random_array

array([[39, 70, 72],
       [69, 12, 28]])

In [10]:
random_array = np.random.randint(2 , 92 , size=(2,3))
random_array

array([[82, 35, 49],
       [52, 40, 28]])

In [12]:
# Random floats

random_array2 = np.random.random((3,3))
random_array2

array([[0.32865421, 0.36222694, 0.85698179],
       [0.77119657, 0.98194476, 0.67763644],
       [0.59670353, 0.60170352, 0.06417203]])

In [13]:
random_array3 = np.random.rand(2,3)
random_array3

array([[0.29997028, 0.24360372, 0.37591907],
       [0.35657553, 0.43968088, 0.80080601]])

In [14]:
# Pseudo random numbers

In [16]:
# if only one number is given then it by default selects it as high
random_array_4 = np.random.randint(10 , size = (5,3))
random_array_4

array([[5, 5, 2],
       [2, 9, 6],
       [8, 6, 7],
       [9, 2, 0],
       [2, 7, 1]])

In [23]:
np.random.seed(seed=2)
random_array_5 = np.random.randint(10 , size = (5,3))
random_array_5

array([[8, 8, 6],
       [2, 8, 7],
       [2, 1, 5],
       [4, 4, 5],
       [7, 3, 6]])

In [24]:
# Seed is used when we need to reproduce the random array in other computer else seed is set to random everytime it is called.

#### Viewing array and matrices

In [26]:
# Returns the unique element in the array
np.unique(random_array_5)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [31]:
a1[0]

1

In [32]:
a2[1]

array([3. , 4. , 0.9])

In [34]:
a3[1]

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [37]:
# Slicing in an array

# Taking out first two elements of each 

a3.shape

(2, 3, 3)

In [39]:
a3[ :2 , :2 , :2 ]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [41]:
a4 = np.random.randint(10 , size =(2,3,4,5))
a4.shape , a4.ndim

((2, 3, 4, 5), 4)

In [42]:
# Now numpy array is displayed in backward direction
# <----------- Like this , From outside to inside

In [43]:
a4

array([[[[4, 3, 7, 6, 1],
         [3, 5, 8, 4, 6],
         [3, 9, 2, 0, 4],
         [2, 4, 1, 7, 8]],

        [[2, 9, 8, 7, 1],
         [6, 8, 5, 9, 9],
         [9, 3, 0, 0, 2],
         [8, 8, 2, 9, 6]],

        [[5, 6, 6, 6, 3],
         [8, 2, 1, 4, 8],
         [1, 6, 9, 5, 1],
         [2, 4, 7, 6, 4]]],


       [[[5, 8, 3, 0, 0],
         [5, 7, 5, 0, 8],
         [6, 5, 1, 7, 4],
         [3, 6, 1, 4, 0]],

        [[8, 5, 4, 2, 9],
         [7, 1, 9, 2, 1],
         [0, 7, 1, 8, 9],
         [0, 7, 0, 5, 2]],

        [[5, 1, 3, 3, 1],
         [8, 6, 8, 1, 5],
         [7, 0, 9, 1, 5],
         [9, 2, 0, 0, 4]]]])

In [47]:
# Getting the first 4 elements of inner most array 

a4[: , : , : , :4]

array([[[[4, 3, 7, 6],
         [3, 5, 8, 4],
         [3, 9, 2, 0],
         [2, 4, 1, 7]],

        [[2, 9, 8, 7],
         [6, 8, 5, 9],
         [9, 3, 0, 0],
         [8, 8, 2, 9]],

        [[5, 6, 6, 6],
         [8, 2, 1, 4],
         [1, 6, 9, 5],
         [2, 4, 7, 6]]],


       [[[5, 8, 3, 0],
         [5, 7, 5, 0],
         [6, 5, 1, 7],
         [3, 6, 1, 4]],

        [[8, 5, 4, 2],
         [7, 1, 9, 2],
         [0, 7, 1, 8],
         [0, 7, 0, 5]],

        [[5, 1, 3, 3],
         [8, 6, 8, 1],
         [7, 0, 9, 1],
         [9, 2, 0, 0]]]])

### Manipulating array

#### Arithmatic

In [48]:
a1

array([1, 2, 3, 4])

In [51]:
one = np.ones(4)

In [52]:
one

array([1., 1., 1., 1.])

In [53]:
a1 + one

array([2., 3., 4., 5.])

In [54]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [55]:
a2

array([[1. , 2. , 0.5],
       [3. , 4. , 0.9]])

In [57]:
a1 = [1,2,3]

In [58]:
a1*a2

array([[1. , 4. , 1.5],
       [3. , 8. , 2.7]])

In [59]:
# Smaller array is broadcasted around larger array to make comparble shapes of the array 

In [62]:
a3 * a2

ValueError: operands could not be broadcast together with shapes (2,3,3) (2,3) 

In [66]:
a2 = np.reshape(a2 , (2,3,1) , order='C')

In [67]:
a3*a2

array([[[ 1. ,  2. ,  3. ],
        [ 8. , 10. , 12. ],
        [ 3.5,  4. ,  4.5]],

       [[30. , 33. , 36. ],
        [52. , 56. , 60. ],
        [14.4, 15.3, 16.2]]])

In [68]:
a2 / a1

array([[[1.        , 0.5       , 0.33333333],
        [2.        , 1.        , 0.66666667],
        [0.5       , 0.25      , 0.16666667]],

       [[3.        , 1.5       , 1.        ],
        [4.        , 2.        , 1.33333333],
        [0.9       , 0.45      , 0.3       ]]])

In [70]:
# Floor Division removes decimals ( kind of round off)
a2 // a1

array([[[1., 0., 0.],
        [2., 1., 0.],
        [0., 0., 0.]],

       [[3., 1., 1.],
        [4., 2., 1.],
        [0., 0., 0.]]])

In [75]:
# Power or square
a1 ** 2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [80]:
a2 ** 2

array([[[ 1.  ],
        [ 4.  ],
        [ 0.25]],

       [[ 9.  ],
        [16.  ],
        [ 0.81]]])

In [82]:
np.square(a2)

array([[[ 1.  ],
        [ 4.  ],
        [ 0.25]],

       [[ 9.  ],
        [16.  ],
        [ 0.81]]])

In [84]:
np.add(a1 , a2)

array([[[2. , 3. , 4. ],
        [3. , 4. , 5. ],
        [1.5, 2.5, 3.5]],

       [[4. , 5. , 6. ],
        [5. , 6. , 7. ],
        [1.9, 2.9, 3.9]]])

In [86]:
# Returns the element wise remainder similar to x % y
np.mod(a2 , a1)

array([[[0. , 1. , 1. ],
        [0. , 0. , 2. ],
        [0.5, 0.5, 0.5]],

       [[0. , 1. , 0. ],
        [0. , 0. , 1. ],
        [0.9, 0.9, 0.9]]])

#### Aggregation 

Performing same operation on number of things 

In [2]:
a1 = np.array([1,2,3])

In [3]:
type(a1)

numpy.ndarray

In [4]:
sum(a1)

6

In [5]:
np.sum(a1)

6

IMPORTANT

Use python operations such as (`sum()`) on python datatype

Use numpy operations such as (`np.sum()`) on numpy datatype

##### Demonstrating the power of NUMPY

In [6]:
massive_array = np.random.random(10000)

In [7]:
## Using the magic function to see how much time it takes 

# Sum using python sum()

%timeit sum(massive_array)

# Sum using Numpy np.sum()

%timeit np.sum(massive_array)

554 µs ± 8 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
6.02 µs ± 33.7 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [9]:
np.mean(a2)

1.9000000000000001

In [17]:
# Variance ( var ) :- average measure of how different is a number from the mean
# Standard Deviation :- how spread out the numbers are from the mean 

# Both are measure of spread of data 

# Std is basically ' Square Root ' of variance 

np.max(a2) , np.min(a2) , np.std(a2) , np.var(a2)

(4.0, 0.5, 1.2516655570345725, 1.5666666666666664)

#### Demonstration of Var & Std

In [18]:
high_var_array = np.array([1 , 100 , 200 , 3000 , 4500 , 7000])
low_var_array = np.array([2,4,6,8,10])

In [19]:
np.var(high_var_array)

6964733.472222221

In [20]:
np.var(low_var_array)

8.0

In [21]:
# Higher var means higher range of number 

# Lower var means lower range of number

####  Reshaping & Transposing a numpy array

In [22]:
a2.shape , a2.ndim , a2.size

((2, 3), 2, 6)

In [24]:
a3.shape , a3.ndim , a3.size

((2, 3, 3), 3, 18)

In [25]:
a2 * a3

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

In [28]:
a2_reshape = a2.reshape((2,3,1))

In [29]:
a2_reshape * a3

array([[[ 1. ,  2. ,  3. ],
        [ 8. , 10. , 12. ],
        [ 3.5,  4. ,  4.5]],

       [[30. , 33. , 36. ],
        [52. , 56. , 60. ],
        [14.4, 15.3, 16.2]]])

In [34]:
# Transpose of an array 
# Changes the axis or ( Row <-> Column )

a2.T

array([[1. , 3. ],
       [2. , 4. ],
       [0.5, 0.9]])

In [35]:
a2

array([[1. , 2. , 0.5],
       [3. , 4. , 0.9]])

In [36]:
a3_transpose = a3.T

In [38]:
a3_transpose.shape , a3.shape

((3, 3, 2), (2, 3, 3))

In [39]:
# So transposed basically reveresed the shape

###  Dot Product 

In [3]:
np.random.seed(0)

mat1 = np.random.randint(10 , size=(5,3))
mat2 = np.random.randint(10 , size=(5,3))

In [4]:
# Element wise multiplication

In [5]:
mat1 * mat2

array([[30,  0, 21],
       [24,  7, 45],
       [27, 40, 18],
       [16, 21,  0],
       [24, 40,  0]])

In [6]:
# Dot product is like matrix multiplication ( waterfall method)

In [7]:
np.dot(mat1 , mat2)

ValueError: shapes (5,3) and (5,3) not aligned: 3 (dim 1) != 5 (dim 0)

In [8]:
# Now to fix this lets see some rule for dot product 

# 5 x 3 <-------> 3 x 5

# The inner numbers must match =>  3 = 3 in this case

# The resultant matrix is of the order of outer numbers =>  5 x 5 in this case

In [9]:
mat2.T

array([[6, 8, 9, 4, 3],
       [7, 1, 8, 3, 5],
       [7, 5, 9, 0, 0]])

In [10]:
mat2_T = mat2.T

In [11]:
mat2_T.shape , mat1.shape

((3, 5), (5, 3))

In [12]:
mat3 = np.dot(mat1 , mat2_T)
mat3

array([[ 51,  55,  72,  20,  15],
       [130,  76, 164,  33,  44],
       [ 67,  39,  85,  27,  34],
       [115,  69, 146,  37,  47],
       [111,  77, 145,  56,  64]])

In [13]:
mat3.shape

(5, 5)

## Practical Example of Dot product ( Via Nut-Butter-Sales )

In [14]:
import numpy as np
import pandas as pd

In [54]:
np.random.seed(0)

sales_amount = np.random.randint(20 , size=(5,3))
sales_amount

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [55]:
sales = pd.DataFrame(sales_amount , index=["Mon" , "Tues" , "Wed" , "Thurs" , "Fri"] , columns=["Almond Butter" , "Peanut Butter" , "Cashew Butter"])
sales

Almond Butter  Peanut Butter  Cashew Butter
Mon               12             15              0
Tues               3              3              7
Wed                9             19             18
Thurs              4              6             12
Fri                1              6              7

In [56]:
sales_daily = pd.DataFrame(sales_amount , index=["Mon" , "Tues" , "Wed" , "Thurs" , "Fri"] , columns=["Almond Butter" , "Peanut Butter" , "Cashew Butter"])
sales_daily

Almond Butter  Peanut Butter  Cashew Butter
Mon               12             15              0
Tues               3              3              7
Wed                9             19             18
Thurs              4              6             12
Fri                1              6              7

In [57]:
prices = np.array([10,8,12])
prices

array([10,  8, 12])

In [58]:
Jar_prices = pd.DataFrame(prices , index=["Prices"], columns=["Almond Butter" , "Peanut Butter" , "Cashew Butter"])
Jar_prices

ValueError: Shape of passed values is (3, 1), indices imply (1, 3)

In [59]:
prices.shape

(3,)

In [60]:
prices = prices.reshape((1,3))

In [61]:
Jar_prices = pd.DataFrame(prices , index=["Prices"], columns=["Almond Butter" , "Peanut Butter" , "Cashew Butter"])
Jar_prices

Almond Butter  Peanut Butter  Cashew Butter
Prices             10              8             12

In [62]:
sales_daily["Total Sales"] = np.dot(sales_amount , prices.T)
sales_daily

Almond Butter  Peanut Butter  Cashew Butter  Total Sales
Mon               12             15              0          240
Tues               3              3              7          138
Wed                9             19             18          458
Thurs              4              6             12          232
Fri                1              6              7          142

In [63]:
# Another way 

In [64]:
Jar_prices.shape , sales.shape

((1, 3), (5, 3))

In [66]:
daily_sales = Jar_prices.dot(sales.T)

In [67]:
sales["Total ($) "] = daily_sales.T
sales

Almond Butter  Peanut Butter  Cashew Butter  Total ($) 
Mon               12             15              0         240
Tues               3              3              7         138
Wed                9             19             18         458
Thurs              4              6             12         232
Fri                1              6              7         142

### Comparision Operators in Numpy

In [69]:
arr1 = np.random.randint(10 , size=(5))
arr1

array([8, 1, 5, 9, 8])

In [70]:
arr2 = np.random.randint(10 ,size=(2,5))
arr2

array([[9, 4, 3, 0, 3],
       [5, 0, 2, 3, 8]])

In [71]:
arr1 > arr2

array([[False, False,  True,  True,  True],
       [ True,  True,  True,  True, False]])

In [73]:
bool_array = arr1 >= arr2
bool_array

array([[False, False,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [74]:
type(bool_array) , bool_array.dtype

(numpy.ndarray, dtype('bool'))

In [75]:
# So the type of bool_array is an ndarray where as the data in it is of type bool

In [76]:
arr1 > 5

array([ True, False, False,  True,  True])

In [77]:
arr1 == 5

array([False, False,  True, False, False])

In [78]:
arr1 == arr2

array([[False, False, False, False, False],
       [False, False, False, False,  True]])

In [79]:
#### These are all elemetwise comparision . Lookup for more in numpy documentation

### Sorting an Numpy array

In [83]:
np.random.seed(0)
random_array = np.random.randint(10 , size=(3,5))
random_array

array([[5, 0, 3, 3, 7],
       [9, 3, 5, 2, 4],
       [7, 6, 8, 8, 1]])

In [84]:
np.sort(random_array)

array([[0, 3, 3, 5, 7],
       [2, 3, 4, 5, 9],
       [1, 6, 7, 8, 8]])

In [86]:
# To sort the index like which index value should come first we use argsort
np.argsort(random_array)

array([[1, 2, 3, 0, 4],
       [3, 1, 4, 2, 0],
       [4, 1, 0, 2, 3]], dtype=int64)

In [88]:
# To sort on the basis of column
np.argmin(random_array , axis=1) , np.argmax(random_array , axis=1)

(array([1, 3, 4], dtype=int64), array([4, 0, 2], dtype=int64))

###  Numpy Practical implimentation ( Via Images to Number )

<img src = "panda.png" />

In [93]:
from matplotlib.image import imread

In [94]:
panda = imread("panda.png")

In [95]:
type(panda)

numpy.ndarray

In [96]:
panda.size, panda.shape , panda.ndim

(24465000, (2330, 3500, 3), 3)

In [97]:
print(type(panda))

<class 'numpy.ndarray'>
